### ISSUE TITLE
Handle /tmp/kelda.sock collisions more gracefully

### ISSUE THREAD

**Issue by ejj** [kelda/kelda#1416]
If you've got a daemon and you attempt to start a second, it will error with something like `bind: address already in use`.   This error message isn't very helpful.  Would be much better to suggest that either another daemon is running, or that it failed to clean up it's socket.

Note that we could tell which of the two issues it is by attempting to delete the socket.  If we can do so successfully, we can move forward with starting ourselves.  If we can't then we should display the more helpful error message.

Reported-By: @nthmost

**Comment by kklin** [comment]
I actually don't think that attempting to delete the socket gives useful information. From my test locally, I could start a daemon with `kelda daemon`, and then `rm /tmp/kelda.sock` without a problem.

We might be able to check if the file is open or something.

**Comment by ejj** [comment]
Yep you're right on this point.  At any rate, many new users run into this, so definitely worth figuring something out.
