### ISSUE TITLE
Split up kelda-init into a provider configuration and base infrastructure configuration tool

### ISSUE THREAD

**Issue by ejj** [kelda/kelda#1417]
Having kelda init handle both cloud provider setup and base infrastructure setup is confusing.  Users can end up configuring a number of VMs thinking it will change things even if the blueprint doesn't use base infrastructure at all.  We've seen users get caught by this before.  Currently, we think that breaking the command up will make the commands more intuitive so users are less likely to get lost.

Reported-by: @nthmost

Note, there's some Kelda internal thoughts on this here: https://paper.dropbox.com/doc/Configuring-Kelda-c5HRAUSY5V64jVlyxfZkY

**Comment by luise** [comment]
Fixed in https://github.com/kelda/kelda/pull/1430
